src/PiDev/ClientBundle/Entity/Appeldoffre.php
<?php


namespace PiDev\ClientBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity
 */
class Appeldoffre {
      /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
   
        /**
     *@ORM\Column(type="string",length=255)
     */
    private $nom;
        /**
     *@ORM\Column(type="string",length=255)
     */
    private $Description;
    /**
     *@ORM\ManyToOne(targetEntity="PiDev\ClientBundle\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="proprietaire_id", referencedColumnName="id",onDelete="CASCADE")
     * })
          */
    private $proprietaire;
    
     /**
     *@ORM\Column(type="string",length=255)
     */
    private $Mail;
    
     /**
     *@ORM\Column(type="integer")
     */
    private $Telephone;
    
     /**
     *@ORM\Column(type="string",length=255)
     */
    private $Adresse;
    
    public function getId() {
        return $this->id;
    }

    public function getDescription() {
        return $this->Description;
    }

    public function getNom() {
        return $this->nom;
    }

 

    public function getProprietaire() {
        return $this->proprietaire;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function setDescription($Description) {
        $this->Description = $Description;
    }

    public function setNom($nom) {
        $this->nom = $nom;
    }

 

    public function setProprietaire($proprietaire) {
        $this->proprietaire = $proprietaire;
    }

    public function getMail() {
        return $this->Mail;
    }

    public function getTelephone() {
        return $this->Telephone;
    }

    public function getAdresse() {
        return $this->Adresse;
    }

    public function setMail($Mail) {
        $this->Mail = $Mail;
    }

    public function setTelephone($Telephone) {
        $this->Telephone = $Telephone;
    }

    public function setAdresse($Adresse) {
        $this->Adresse = $Adresse;
    }


    
}

src/PiDev/ClientBundle/Form/AppeldoffreType.php
<?php

namespace PiDev\ClientBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AppeldoffreType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('nom','text',array('required' => true,'attr' => array('class' => 'text')))
                ->add('Description','text',array('required' => true,'attr' => array('class' => 'text')))
                ->add('Mail','text',array('required' => true,'attr' => array('class' => 'text')))
                ->add('Telephone','integer',array('required' => true,'attr' => array('class' => 'text')))
                ->add('Adresse','text',array('required' => true,'attr' => array('class' => 'text')))
     ;
 
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PiDev\ClientBundle\Entity\Appeldoffre'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'piDevClientBundle_appeldoffre';
    }
}

src/PiDev/ClientBundle/Controller/AppeldoffreController.php
<?php

namespace PiDev\ClientBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use PiDev\ClientBundle\Entity\Appeldoffre;
use PiDev\ClientBundle\Form\AppeldoffreType;
use Symfony\Component\HttpFoundation\Request;

class AppeldoffreController extends Controller {

    public function AjouterAction(Request $request) {
      $user = $this->get('security.context')->getToken()->getUser();


        $model = new Appeldoffre();
        $modelForm = new AppeldoffreType();
        $form = $this->createForm($modelForm, $model);
        $form->handleRequest($request);
        
        if ($request->getMethod() == 'POST') {
            $em = $this->getDoctrine()->getManager();
            $model->setProprietaire($user);
            $em->persist($model);
            $em->flush();
            return $this->redirect($this->generateUrl('detail_appel_offre', array('id' => $model->getId())));
        }
        return$this->render('PiDevClientBundle:Appeldoffre:new.html.twig', array(
            'f' => $form->createView()));
    }

    public function RechercheAction(Request $request) {
              $em1 = $this->get('doctrine.orm.entity_manager');
        $dql = "SELECT a FROM PiDevClientBundle:Appeldoffre a";
        $query = $em1->createQuery($dql);

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $query, /* query NOT result */ $request->query->getInt('page', 1)/* page number */, 5/* limit per page */
        );
        $em = $this->getDoctrine()->getManager();
        $services = $em->getRepository ('PiDevClientBundle:Appeldoffre')->findAll();
        $request = $this->get('request');
        if ($request->getMethod() == "POST") {
            $search = $request->get('search');
            $services = $em->getRepository ('PiDevClientBundle:Appeldoffre')->findBy(array("nom" => $search));
        }

        return $this->render ('PiDevClientBundle:Appeldoffre:showAll.html.twig', array(
            "services" => $services,
            "pagination"=>$pagination
                
                ));
    }

    function DetailsAction($id) {
        $em = $this->getDoctrine()->getManager();
        $model = $em->getRepository
                        ('PiDevClientBundle:Appeldoffre')->find($id);
        return $this->render
                        ('PiDevClientBundle:Appeldoffre:Detail.html.twig', array('mod' => $model));
    }

    public function supprimerAction($id) {
        $em = $this->getDoctrine()->getManager();
        $modeles = $em->getRepository
                        ('PiDevClientBundle:Appeldoffre')->find($id);
        $em->remove($modeles);
        $em->flush();
        return $this->redirect($this->generateUrl("prop/{proprietaire}"));
    }

    public function ModifierAction($id) {
        $em = $this->getDoctrine()->getManager();
        $modele = $em->getRepository('PiDevClientBundle:Appeldoffre')
                ->find($id);
        $formv = new AppeldoffreType;
        $form = $this->createForm($formv, $modele);
        $Request = $this->get('request');
        if ($form->handleRequest($Request)->isValid()) {
            $em->persist($modele);
            $em->flush();
            return $this->redirect($this->generateUrl("new_appel_offre"));
        }
        return $this->render
                        ('PiDevClientBundle:Appeldoffre:modifier.html.twig', array('form' => $form->createView()));
    }

}

src/PiDev/ClientBundle/Resources/views/Appeldoffre/Detail.html.twig
{% extends '::base.html.twig' %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">

        <!-- Mirrored from forum.azyrusthemes.com/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 28 Mar 2016 20:23:41 GMT -->
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Forum :: Home Page</title>

            <!-- Bootstrap -->
            <link href="{{asset('bundles/appelOffre/css/bootstrap.min.css')}}" rel="stylesheet">

            <!-- Custom -->
            <link href="{{asset('bundles/appelOffre/css/custom.css')}}" rel="stylesheet">

            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
              <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
              <![endif]-->

            <!-- fonts -->
            <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="{{asset('bundles/appelOffre/font-awesome-4.0.3/css/font-awesome.min.css')}}">

            <!-- CSS STYLE-->
            <link rel="stylesheet" type="text/css" href="{{asset('bundles/appelOffre/css/style.css')}}" media="screen" />

            <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
            <link rel="stylesheet" type="text/css" href="{{asset('bundles/appelOffre/rs-plugin/css/settings.css')}}" media="screen" />

        </head>
        <body>

            <div class="container-fluid">

                <!-- Slider -->
                <div class="tp-banner-container">
                    <div class="tp-banner" >
                        <ul>	
                            <!-- SLIDE  -->
                            <li data-transition="fade" data-slotamount="7" data-masterspeed="1500" >
                                <!-- MAIN IMAGE -->
                                <img src="{{asset('bundles/appelOffre/images/slide.jpg')}}"  alt="slidebg1"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
                                <p> coucou</p>   <!-- LAYERS -->
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- //Slider -->

                <section class="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-xs-12 col-md-8">
                                <div class="pull-left"><a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a></div>
                                <div class="pull-left">
                                    <ul class="paginationforum">

                                    </ul>
                                </div>
                                <div class="pull-left"><a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a></div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>


                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-md-8">
                                <!-- POST -->
                                <div class="post beforepagination">
                                    <div class="topwrap">
                                        <div class="userinfo pull-left">
                                            <div class="avatar">
                                                <img src="images/avatar.jpg" alt="" />
                                                <div class="status green">&nbsp;</div>
                                            </div>

                                            <div class="icons">
                                                <img src="{{asset('bundles/appelOffre/images/icon1.jpg')}}" alt="" /><img src="{{asset('bundles/appelOffre/images/icon4.jpg')}}" alt="" />
                                                <img src="{{asset('bundles/appelOffre/images/icon5.jpg')}}" alt="" /><img src="{{asset('bundles/appelOffre/images/icon6.jpg')}}" alt="" />
                                            </div>
                                        </div>
                                        <div class="posttext pull-left">
                                            <h2> {{mod.nom}}</h2><hr>
                                            Mail de contact : {{mod.mail}}</h2><hr>
                                            Telephone : {{mod.telephone}}</h2><hr>
                                            Adresse : {{mod.adresse}}</h2><hr>
                                            <p>{{mod.description}}</div><hr>
                                        <div class="clearfix"></div>
                                    </div>                              
                                    <div class="postinfobot">




                                        <div class="posted pull-left"><i class="fa fa-clock-o"></i> Posted on : 20 Nov @ 9:30am</div>



                                        <div class="clearfix"></div>
                                    </div>
                                </div><!-- POST -->





                            </div>
                            <div class="col-lg-4 col-md-4">

                                <!-- -->
                                <div class="sidebarblock">
                                    <br>
                                    <center> <b><i>Rechercher</i></b></center><br>
                                    <center>    <div class="input-group">
                                            <form method="POST"  action="{{path('recherche_appel_offre')}}">
                                                <input type="text" name="search" >

                                                <button class="btn btn-info" type="submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </form>
                                        </div>  </center> <hr><hr>
                                    <center> <b><i>Ajouter un appel d'offre</i></b></center><br>

                                    <div class="divline"></div>
                                    <div class="blocktxt">

                                        Si vous desirez ajouter un sujet clique au-dessous<br><br>
                                        <center>  <a href="{{path('new_appel_offre')}}" >  <button type="submit" action="{{path('new_appel_offre')}}" class="btn btn-info"><i class="fa fa-plus-square"></i>  Appel d'offre</button></a>
                                        </center>   

                                    </div>
                                    <hr><hr>
                                    <center> <b><i>Categories</i></b></center><br>
                                    <div class="divline"></div>
                                    <div class="blocktxt">
                                        <ul class="cats">
                                            <li><a href="#">Trading for Money <span class="badge pull-right">20</span></a></li>
                                            <li><a href="#">Vault Keys Giveway <span class="badge pull-right">10</span></a></li>
                                            <li><a href="#">Misc Guns Locations <span class="badge pull-right">50</span></a></li>
                                            <li><a href="#">Looking for Players <span class="badge pull-right">36</span></a></li>
                                            <li><a href="#">Stupid Bugs &amp; Solves <span class="badge pull-right">41</span></a></li>
                                            <li><a href="#">Video &amp; Audio Drivers <span class="badge pull-right">11</span></a></li>
                                            <li><a href="#">2K Official Forums <span class="badge pull-right">5</span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- -->


                            <!-- -->



                        </div>
                    </div>
            </div>





        </section>



        <!-- get jQuery from the google apis -->
        <script type="text/javascript" src="{{asset('bundles/appelOffre/ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js')}}"></script>


        <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
        <script type="text/javascript" src="{{asset('bundles/appelOffre/rs-plugin/js/jquery.themepunch.plugins.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('bundles/appelOffre/rs-plugin/js/jquery.themepunch.revolution.min.js')}}"></script>

        <script src="{{asset('bundles/appelOffre/js/bootstrap.min.js')}}"></script>


        <!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->
        <script type="text/javascript">

            var revapi;

            jQuery(document).ready(function() {
                "use strict";
                revapi = jQuery('.tp-banner').revolution(
                        {
                            delay: 15000,
                            startwidth: 1200,
                            startheight: 278,
                            hideThumbs: 10,
                            fullWidth: "on"
                        });

            });	//ready

        </script>

        <!-- END REVOLUTION SLIDER -->
    </body>

    <!-- Mirrored from forum.azyrusthemes.com/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 28 Mar 2016 20:24:16 GMT -->
</html>    





{% endblock %}

src/PiDev/ClientBundle/Resources/views/Appeldoffre/modifier.html.twig
{% extends '::base.html.twig' %}

{% block content %}

<h1>Modifier Mon Appel d'offre </h1>
<form action="" method="post" >
    <table> 
    <tr>
        <td>nom: </td>
        <td>{{ form_widget(form.nom)}}</td>  
    </tr>
    <tr>  
    <td>   Description:</td>
    <td>{{ form_widget(form.Description)}}</td>
    </tr>
    <tr>  
    <td>   Mail:</td>
    <td>{{ form_widget(form.Mail)}}</td>
    </tr>
    <tr>  
    <td>   Telephone:</td>
    <td>{{ form_widget(form.Telephone)}}</td>
    </tr>
    <tr>  
    <td>   Description:</td>
    <td>{{ form_widget(form.Adresse)}}</td>
    </tr>
</table>
    <br>
  
{{form_rest(form)}}
</form>
 {% endblock %}

src/PiDev/ClientBundle/Resources/views/Appeldoffre/new.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <html > 
        <head 
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
            <title>CSS Form Tutorial: How to Improve Web Order Form Design</title> 
            <link rel="stylesheet" href={{asset('bundles/commande/css/reset.css')}} type="text/css" media="all" /> 
            <link rel="stylesheet" href={{asset('bundles/commande/css/style.css')}} type="text/css" media="all" /> 
        </head>

        <body>

            <div id="wrap">

                <div class="container">





                    <div class="box-719" >
                        <div class="rcfg-blue pl-6 pr-6 pt-6 pb-5">

                            <div class="box-660">
                                <b class="rc-lightblue"><b class="rc1-lightblue"><b></b></b><b class="rc2-lightblue"><b></b></b><b class="rc3-lightblue"></b><b class="rc4-lightblue"></b><b class="rc5-lightblue"></b></b>
                                <div class="rcfg-lightblue pl-4 pr-4 pb-4">










                                    <p class="ml-3">Ajouter un nouvel appel d'offre!</p>



                                    <!-- Form Starting -->
                                    <form id="validate" class="order" method="post" action="">
                                        <fieldset>
                                            <ul class="order">
                                                <li><label >Nom :<span class="typo-1">*</span></label>{{form_widget(f.nom)}}</li>
                                                <li><label>Mail :<span class="typo-1">*</span></label>{{form_widget(f.Mail)}}</li>
                                                <li><label>Telephone :<span class="typo-1">*</span></label>{{form_widget(f.Telephone)}}</li>
                                                <li><label>Adresse :<span class="typo-1">*</span></label>{{form_widget(f.Adresse)}}</li>
                                                <li><label>Description :<span class="typo-1">*</span></label>{{form_widget(f.Description)}}</li>
                                           </ul>
                                            <div class="clear"></div>
                                            <p>NB : cet appel d'offre ne sera afficher qu'aprés la validation de l'administrateur</p>
                                            <div class="clear"></div>
                                            <div class="form-actions align-right">
                                                {{ form_widget(f._token) }}

                                                <input class="bt-order-blue" type="submit" value="valider"  />
                                            </div>
                                            <div class="clear"></div>
                                        </fieldset>
                                    </form>
                                    <!-- Form Ending -->




                                </div>
                                <b class="rc-lightblue"><b class="rc5-lightblue"></b><b class="rc4-lightblue"></b><b class="rc3-lightblue"></b><b class="rc2-lightblue"><b></b></b><b class="rc1-lightblue"><b></b></b></b>
                            </div>


                            <div class="clear"></div>


                        </div>
                        <b class="rc-blue"><b class="rc5-blue"></b><b class="rc4-blue"></b><b class="rc3-blue"></b><b class="rc2-blue"><b></b></b><b class="rc1-blue"><b></b></b></b>
                    </div>
                    <div class="clear"></div>




                </div>
            </div>
        </div>
    </body>
</html>
{% endblock %}